### ISSUE TITLE
Yarn vs NPM

### ISSUE THREAD

**Issue by pghege** [Battery-Intelligence-Lab/galvanalyser#10]
**Is your feature request related to a problem? Please describe.**
I notice some modules are using yarn while others are using npm. This discrepancy may cause build failure in the future. Under galvanalyser frontend uses yarn in Dockerfile_dev but npm in Dockerfile. Additionally there is a yarn.lock file present in the directory which suggests Yarn is preferred. Should the prod Dockerfile be changed to use yarn?

**Describe the solution you'd like**
To rely on one build tool. I have slight preference for Yarn but just looking for clarity and consistency

**Comment by martinjrobins** [comment]
thanks  for this @pghege. Yes, I was indeed aiming for yarn, so I'll update `frontend/Dockerfile`
