### ISSUE TITLE
Harvester Deletion Button

### ISSUE THREAD

**Issue by asafdari-boop** [Battery-Intelligence-Lab/galvanalyser#18]
The delete harvester button does not appear to work. The React component row for that harvester stays on the webpage and I think you can still run it, meaning it may not actually be deleted. 

1. Got to Harvester
2. Create Harvester
3. Press Delete 

**Expected behavior**
I expect the harvester to disappear along with its datapath.

**Comment by martinjrobins** [comment]
fixed in f787c24
