### ISSUE TITLE
Harvester Failed Import

### ISSUE THREAD

**Issue by asafdari-boop** [Battery-Intelligence-Lab/galvanalyser#19]
Whenever a file fails to import it seems from the worker log to be ignored the next time the harvester is run, leading to the creation for multiple harvesters to monitor the same file path. 

1. Go to Harvester
2. Create Harvester
3. Import a file with bad formatting causing a fail
4. Try and rerun the harvester with the same file after fixing file formatting

**Expected behavior**
Ideally the harvester would notice changes to the file size and rerun the import process.

**Comment by martinjrobins** [comment]
fixed in ccfabe9
