### ISSUE TITLE
Hi Martin, Could you please add a feature for API code generation in MATLAB (in addition to the existing Python). Thank you! 

### ISSUE THREAD

**Issue by emmanuellehagopian** [Battery-Intelligence-Lab/galvanalyser#27]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by martinjrobins** [comment]
Hi @emmanuellehagopian. Sure I can look at this. The advantage of Python is that there are loads of tools to automatically generate a REST client from an openapi descriptions (which is what we have), but not sure about MATLAB. I can have a look at it
