### ISSUE TITLE
Compose fail on frontend - yarn install NODE_OPTIONS

### ISSUE THREAD

**Issue by BradyPlanden** [Battery-Intelligence-Lab/galvanalyser#65]
**Describe the bug**
I'm getting an exit code 9 on the `RUN yarn install` in the docker-compose. Here is the trace:

```
Building frontend
[+] Building 4.7s (11/15)                                                                            
 => [internal] load build definition from Dockerfile                                            0.7s
 => => transferring dockerfile: 411B                                                            0.0s
 => [internal] load .dockerignore                                                               0.5s
 => => transferring context: 53B                                                                0.0s
 => [internal] load metadata for docker.io/library/nginx:alpine                                 0.0s
 => [internal] load metadata for docker.io/library/node:lts                                     0.0s
 => [build 1/7] FROM docker.io/library/node:lts                                                 0.0s
 => [internal] load build context                                                               0.2s
 => => transferring context: 2.11kB                                                             0.0s
 => CACHED [stage-1 1/3] FROM docker.io/library/nginx:alpine                                    0.0s
 => CACHED [build 2/7] RUN mkdir -p /app                                                        0.0s
 => CACHED [build 3/7] WORKDIR /app                                                             0.0s
 => CACHED [build 4/7] COPY package.json yarn.lock /app/                                        0.0s
 => ERROR [build 5/7] RUN yarn install                                                          3.7s
------                                                                                               
 > [build 5/7] RUN yarn install:
#11 1.439 node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
------
process "/bin/sh -c yarn install" did not complete successfully: exit code: 9
ERROR: Service 'frontend' failed to build : Build failed
```
Removing `ENV NODE_OPTIONS=--openssl-legacy-provider` from the /frontend/.env file fixes the exit code; however, I've not confirmed if this affects functionality.

**To Reproduce**
1. Clone current repo
2. sudo docker-compose up

**Comment by BradyPlanden** [comment]
After proceeding with `ENV NODE_OPTIONS=--openssl-legacy-provider` removed, I'm unfortunately unable to login to the frontend via the superuser account. Does it make sense that the login functionality would break with the above command removed?

**Comment by martinjrobins** [comment]
this option was added because the frontend wasn't working unless @mjaquiery added this, so it could be breaking the login. Can you open a development console in your browser and try logging in, what error do you get?

**Comment by martinjrobins** [comment]
note I just tried this on a fresh azure vm (ubuntu 20.04) and it worked fine, no issues with the 'NODE_OPTIONS'. What system are you using @BradyPlanden ?

**Comment by BradyPlanden** [comment]
OS is ubuntu 20.04 LTS (it's the current instance used for the BIL).

Quite weird, I'll investigate this a bit further. I suspect it's a host issue now that you've confirmed via azure. I'll update this issue when I find the problem for future reference.

**Comment by martinjrobins** [comment]
@mjaquiery do you know why @BradyPlanden is getting this problem with `NODE_OPTIONS`? I think you added this line.

@BradyPlanden: I don't know what the issue is, but I'm guessing that you have a different `node:lts` image than we do. Perhaps delete all local images and do a `docker compose build --no-cache`. This might help.

Also, if you are having an issue with the login this could be a separate problem. Open a development console in your browser (Ctrl-Shift-I for chrome in windows) and then try to login again. Have a look at the console for any output, and also the network tab for more info on what went wrong

**Comment by mjaquiery** [comment]
@BradyPlanden can you try pulling from `main` and rebuilding and let me know if you still experience the issue, please?

**Comment by mjaquiery** [comment]
Excellent. This problem should not occur in future because the `node:lts` image is now properly specified so we shouldn't get clashes from older images!
